<?php require_once 'logincheck.php';?>

<!DOCTYPE html>
<html>
<head>
    <title>Reports - CLEANSIE</title>
    <!-- Include your existing stylesheets and scripts here -->
</head>
<body>

<div class="ts-main-content">
    
    <div class="content-wrapper">
        <center> <h2 class="page-title">REPORTS</h2></center>

        <!-- Add links to different reports -->
        <ul>
        <li><a href="pool_report.php">POOL ORDERS REPORT</a></li><br>
              <li><a href="tank_report.php">TANK ORDERS REPORT</a></li><br>
            <li><a href="equip_report.php">EQUIPMENT ORDERS REPORT</a></li><br>
            <li><a href="client_report.php">CLIENT REPORT</a></li><br>
            <li><a href="inquiry_report.php">INQUIRIES REPORT</a></li><br>
            <li><a href="cleaner_report.php">CLEANERS REPORT</a></li>

</ul><br>
<center>THE ABOVE ARE REPORTS THAT CAN BE GENERATED BY THE ADMIN.
        <!-- Add your report content here -->

    </div>
</div>

<!-- Include your existing scripts here -->

</body>
</html>
